const GET_ALL_MISSIONS = 'GET_ALL_MISSIONS ' ;
const ERROR = "ERROR";

const LAUNCH_YEAR = 'LAUNCH_YEAR';

const SUCCESS_LAUNCH = 'SUCCESS_LAUNCH'

const SUCCESS_LANDING = 'SUCCESS_LANDING'
const SET_LOADING = 'SET_LOADING'